name: Velociraptor
description: |
  Decrypts blackbox data for a given repository using a passless GPG key
  provided, and optionally tags and pushes an image to a docker repository on
  google.
author: Sevenmind
inputs:
  key:
    description: >
      The GPG key to use in order to decrypt blackbox data
    required: true
  image:
    description: >
      The image name you wish for the built image provided.
    required: false
    default:
  registry:
    description: >
      The docker registry you wish to push your image to. Note that currently
      raptor only support google cloud registry for automatic authorization.
    required: false
  decrypt_only:
    description: >
      Sometimes it can be beneficial to decrypt only, and not push our image. In
      such cases pass true to decrypt_only and velociraptor will simply decrypt
      your files for future actions to use.
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'globe'
  color: 'orange'
